' @compare_tag Node-ClassDiagram v0.1
@startuml
title InertialSensorFuserNode Class Diagram
namespace sensor_msgs::msg {
    class Imu <<(M,#FFFF00)>> <<ROS2>>
}
namespace fast::rf {
    namespace PoseSystem::LocalPoseSubsystem::InertialSensorFuser {
        class BasicInertialSensorFuserProcess {
        }
    }
}
namespace fast::rf_ros2  { 
    abstract BaseNode {

    }
    package PoseSystem::LocalPoseSubsystem::InertialSensorFuser #LightYellow;line:blue {
        class InertialSensorFuserNodeNode #Yellow {
            #void run100Hz()
            #void run10Hz()
            #void run1Hz()
            #void run01Hz()
            #void run001Hz()
            #void runLoop1()
            #void runLoop2()
            #void runLoop3()

            #bool loadConfig()
            #bool initPubSubs()
            #bool initServices()
            #bool initDiagnostics()
            #bool initData()
            -void imuCallback(string topicName, Imu msg)
            -BasicInertialSensorFuserProcess process
            -Publisher m_fusedImuPub
            -Subscriber[] m_imuSubs
            
            
        }
        InertialSensorFuserNodeNode -up-|> BaseNode
        InertialSensorFuserNodeNode *-right-> BasicInertialSensorFuserProcess: <<use>>
    }

}

@enduml