repos:
  - repo: local
    hooks:
      - id: pre-commit-check-template
        name: Check if code is up to date with templates
        entry: python dev_tools/scripts/update_from_template.py --templates templates/Process --impl Systems/ --dry-run
        pass_filenames: false
        language: system

      - id: pre-commit-code-format
        name: Code Formatting
        entry: ./scripts/pre_commit/format_code.sh
        language: script
      
      - id: pre-commit-generate-doxygen
        name: Generate Doxygen
        entry: ./scripts/pre_commit/generate_doxygen.sh
        language: script

      - id: pre-commit-plantuml-conversion
        name: Plantuml Conversion
        entry: ./scripts/pre_commit/plantuml_conversion.sh
        language: script

      - id: pre-commit-dia-conversion
        name: Dia Conversion
        entry: ./scripts/pre_commit/dia_conversion.sh
        language: script

      - id: pre-commit-markdown-check
        name: Check Markdown
        entry: ./scripts/pre_commit/check_markdown.sh
        language: script