@startuml
title Node State Machine Diagram
[*] --> STATE_UNKNOWN
STATE_UNKNOWN --> STATE_INITIALIZED: init()
STATE_INITIALIZED --> STATE_START: start()
STATE_START --> STATE_RUNNING
STATE_RUNNING --> STATE_PAUSED
STATE_PAUSED --> STATE_RUNNING
STATE_RUNNING --> STATE_START: reset()
STATE_RUNNING --> STATE_FINISHED
@enduml