#`@compare_tag Node-YamlConfig v0.1`
/**:
  pose: #System
    localpose: #Subsystem
      inertialsensorfuser: #Generic Process
        inertial_sensor_fuser_node: #Specific Node Name
          ros__parameters:
            example_parameter: 1.234