#`@compare_tag Node-YamlConfig v0.1`
/**:
  ros__parameters:
    safety: #System
      modemanager: #Subsystem
        armedstatemanager: #Generic Process
          armed_state_manager_node: #Specific Node Name
            nodes_to_monitor:
              - "basemachine/basemachine/hatdriver/servo_hat_node"
              - "pose/inertial_sensor/imu/imu_node1"