host_assignments:
  DevComputer2:
    sensors:
      - name: "Fake_IMU_Device"
    nodes:
      - name: "imu_node1"
        parameters:
          sensor_config_package: "robot_framework_ros2"
          sensor_config_relative_path: "config/hardware/Fake_IMU_Device.yaml"

      - name: "inertial_sensor_fuser_node"

