infrastructure_configs:
  frames:
    package: "robot_framework_ros2"
    relative_path: "config/infrastructure/tf_frames.yaml"
  topics:
    package: "robot_framework_ros2"
    relative_path: "config/infrastructure/topics.yaml"

node_registry:

  imu_node1:
    package: "robot_framework_ros2"
    launch_file: "Systems/Pose/Subsystems/InertialSensor/Nodes/IMUNode/launch/imu_node.launch.xml"
    parameters:
      target_frame: "body_frame"
      imu_topic: "imu1" # sensor_msgs/Imu 
      accel_topic: "accel1" # geometry_msgs/AccelStamped
      magnetic_topic: "magnetic1" # sensor_msgs/MagneticField

  inertial_sensor_fuser_node:
    package: "robot_framework_ros2"
    launch_file: "Systems/Pose/Subsystems/LocalPose/Nodes/InertialSensorFuserNode/launch/inertial_sensor_fuser_node.launch.xml"
    parameters:
      imu1_input_topic: "imu1" # sensor_msgs/Imu
      fused_imu_output_topic: "fused_imu" # sensor_msgs/Imu

  local_pose_fuser_node:
    package: "robot_framework_ros2" 
    launch_file: "Systems/Pose/Subsystems/LocalPose/Nodes/LocalPoseFuserNode/launch/local_pose_fuser_node.launch.xml" #Path to Launch File
    parameters:
      machine_inertial_input_topic: "fused_imu" # sensor_msgs/Imu
      local_pose_output_topic: "local_pose" # nav_msgs/Odometry
      local_pose_angular_accel_output_topic: "local_pose_angular_accel" # geometry_msgs/AccelWithCovarianceStamped
