' @compare_tag Node-ClassDiagram v0.1
@startuml
title ExampleNode Node Class Diagram
namespace fast::rf {
    namespace ExampleSystem {
        namespace ExampleSubsystem {
            namespace Example {
                class BasicExampleProcess
            }
        }
    }
}
package fast::rf_ros2 #LightYellow;line:blue { 
    abstract BaseNode {

    }
    class ExampleNodeNode #Yellow {
        #void run100Hz()
        #void run10Hz()
        #void run1Hz()
        #void run01Hz()
        #void run001Hz()
        #void runLoop1()
        #void runLoop2()
        #void runLoop3()

        #bool loadConfig()
        #bool initPubSubs()
        #bool initServices()
        #bool initDiagnostics()
        #bool initData()
        -BasicExampleProcess process
    }
    ExampleNodeNode -up-|> BaseNode
    ExampleNodeNode *-right-> BasicExampleProcess: <<use>>

}

@enduml