@startuml
title Safety System Class Diagram

namespace fast::rf_ros2 {
    package SafetySystem #LightYellow;line:blue {
        namespace ModeManagerSubsystem #Orange {
            namespace ArmedStateManager #Orange {
                class ArmedStateManagerNode <<ROS2>> #Orange
            }
        }
    }
}
@enduml