@startuml
title Safety System Class Diagram

namespace fast::rf_ros2 {
    package SafetySystem #LightYellow;line:blue {
        namespace ModeManagerSubsystem #LimeGreen {
            namespace ArmedStateManager #LimeGreen {
                class ArmedStateManagerNode <<ROS2>> #LimeGreen
            }
        }
    }
}
@enduml