' @compare_tag Subsystem-ClassDiagram v0.1
@startuml
title BaseMachine Subsystem Class Diagram

namespace fast::rf_ros2 {
    namespace BaseMachineSystem {
        package BaseMachineSubsystem #LightYellow;line:blue {
        }
    }
}
@enduml