name: Build and Test CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup ROS 2 Environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: ros2_ws/src/robot_framework_ros2

      - name: Install Dependencies
        run: |
          sudo rosdep init || true
          rosdep update
          rosdep install --from-paths ros2_ws/src --ignore-src -r -y --rosdistro jazzy

      - name: Build Workspace
        run: |
          # Source the core ROS 2 Jazzy environment variables
          source /opt/ros/jazzy/setup.bash
          
          # Move to workspace root and compile
          cd ros2_ws
          colcon build --symlink-install



      