name: Build and Test CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup ROS 2 Environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
          
      - name: Build and test workspace
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros-distro: jazzy
          vcs-repo-file-input: workspace.repos

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: catkin_ws/src/robot_framework_ros2


      